[workspace]
members = [
    "services/app/*",
    "common/rust"
]

[workspace.dependencies]
actix-web = "4.3.1"
anyhow = "1.0.69"
async-trait = "0.1.66" 
common = { path = "common/rust" }
thiserror = "1.0.39"
ulid = "1.0.0"
validator = "0.16.0"