services:
  postgres:
    build:
      context: ./db/postgres
      dockerfile: Dockerfile
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    user: "1000:1000"
    environment:
      POSTGRES_USER: review_stadium
      POSTGRES_PASSWORD: review_stadium
      POSTGRES_DB: review_stadium
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db/postgres/data:/var/lib/postgresql/data
    - ./db/postgres/conf:/etc/postgresql
    - ./db/postgres/entrypoint:/docker-entrypoint-initdb.d
    ports:
    - 54320:5432
