services:
  postgres:
    build:
      context: ./db/postgres
      dockerfile: Dockerfile
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    user: "1000:1000"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
      TZ: 'Asia/Tokyo'
    volumes:
    - ./db/postgres/data:/var/lib/postgresql/data
    - ./db/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    - ./db/postgres/entrypoint:/docker-entrypoint-initdb.d
    networks:
      local_network:
        ipv4_address: 192.168.1.100
    ports:
    - 54320:54320

networks:
  local_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24