name: Web Check

on:
  push:
    paths:
      - ".github/workflows/front-web-ci.yml"
      - "pnpm-lock.yaml"
      - "front/web/**"

jobs:
  check:
    name: Lint, Type check, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # https://github.com/marketplace/actions/setup-pnpm
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - uses: ./.github/actions/cache_pnpm
        name: caching pnpm

      - name: Install dependencies
        run: pnpm --filter @review-stadium/web install

      - name: Check JS
        run: pnpm --filter @review-stadium/web lint

      - name: Check style
        run: pnpm --filter @review-stadium/web style

      - name: Check format
        run: pnpm --filter @review-stadium/web format

      - name: Unit test
        run: pnpm --filter @review-stadium/web test

      # Amplifyを利用するためコメントアウト
      #- name: Build all projects
      #  run: pnpm --filter @review-stadium/web build
